name: zzemal github action

on: [push, pull_request]

jobs:
  hello_and_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      # root 위치로 이동
      - name: Checkout
        uses: actions/checkout@master

      # node 환경 설치?
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      # 의존성 테스트
      - name: Install dependencies
        run: yarn

      # 내가만든 스크립 돌려보기
      - name: Hello
        run: npm hello
